"""Increase precision of ratios in FundamentalData

Revision ID: 3636607f7515
Revises: ef83a7d48458
Create Date: 2025-07-17 00:51:45.957756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3636607f7515'
down_revision: Union[str, None] = 'ef83a7d48458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fundamental_data', 'roce',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.DECIMAL(precision=15, scale=6),
               existing_nullable=True)
    op.alter_column('fundamental_data', 'roe',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.DECIMAL(precision=15, scale=6),
               existing_nullable=True)
    op.alter_column('fundamental_data', 'roa',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.DECIMAL(precision=15, scale=6),
               existing_nullable=True)
    op.alter_column('fundamental_data', 'eps',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.DECIMAL(precision=15, scale=4),
               existing_nullable=True)
    op.alter_column('fundamental_data', 'pe_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.DECIMAL(precision=15, scale=6),
               existing_nullable=True)
    op.alter_column('fundamental_data', 'pb_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.DECIMAL(precision=15, scale=6),
               existing_nullable=True)
    op.alter_column('fundamental_data', 'debt_to_equity',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.DECIMAL(precision=15, scale=6),
               existing_nullable=True)
    op.alter_column('fundamental_data', 'current_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.DECIMAL(precision=15, scale=6),
               existing_nullable=True)
    op.alter_column('fundamental_data', 'quick_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.DECIMAL(precision=15, scale=6),
               existing_nullable=True)
    op.alter_column('fundamental_data', 'gross_margin',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.DECIMAL(precision=15, scale=6),
               existing_nullable=True)
    op.alter_column('fundamental_data', 'operating_margin',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.DECIMAL(precision=15, scale=6),
               existing_nullable=True)
    op.alter_column('fundamental_data', 'net_margin',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.DECIMAL(precision=15, scale=6),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fundamental_data', 'net_margin',
               existing_type=sa.DECIMAL(precision=15, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('fundamental_data', 'operating_margin',
               existing_type=sa.DECIMAL(precision=15, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('fundamental_data', 'gross_margin',
               existing_type=sa.DECIMAL(precision=15, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('fundamental_data', 'quick_ratio',
               existing_type=sa.DECIMAL(precision=15, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('fundamental_data', 'current_ratio',
               existing_type=sa.DECIMAL(precision=15, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('fundamental_data', 'debt_to_equity',
               existing_type=sa.DECIMAL(precision=15, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('fundamental_data', 'pb_ratio',
               existing_type=sa.DECIMAL(precision=15, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('fundamental_data', 'pe_ratio',
               existing_type=sa.DECIMAL(precision=15, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('fundamental_data', 'eps',
               existing_type=sa.DECIMAL(precision=15, scale=4),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=True)
    op.alter_column('fundamental_data', 'roa',
               existing_type=sa.DECIMAL(precision=15, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('fundamental_data', 'roe',
               existing_type=sa.DECIMAL(precision=15, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('fundamental_data', 'roce',
               existing_type=sa.DECIMAL(precision=15, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    # ### end Alembic commands ###
