"""inital commit

Revision ID: 5df1e0b9fe58
Revises: 
Create Date: 2025-07-17 02:43:26.890853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df1e0b9fe58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap_category', sa.String(length=50), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_market_cap_category', 'companies', ['market_cap_category'], unique=False)
    op.create_index('idx_sector', 'companies', ['sector'], unique=False)
    op.create_index(op.f('ix_companies_symbol'), 'companies', ['symbol'], unique=True)
    op.create_table('market_holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_holidays_date'), 'market_holidays', ['date'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("email ~ '^[A-Za-z0-9._%%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'", name='valid_email'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index('idx_users_last_activity', 'users', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('data_update_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('last_update_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_company_data_type', 'data_update_logs', ['company_id', 'data_type'], unique=False)
    op.create_index('idx_last_update_date', 'data_update_logs', ['last_update_date'], unique=False)
    op.create_table('fundamental_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('revenue', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('pat', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('ebitda', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('operating_profit', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('interest_expense', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('total_assets', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('total_liabilities', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('shareholders_equity', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('cash_and_equivalents', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('total_debt', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('operating_cash_flow', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('capex', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('free_cash_flow', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('market_cap', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('shares_outstanding', sa.BigInteger(), nullable=True),
    sa.Column('roce', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('roe', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('roa', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('eps', sa.DECIMAL(precision=15, scale=4), nullable=True),
    sa.Column('pe_ratio', sa.DECIMAL(precision=15, scale=6), nullable=True),
    sa.Column('pb_ratio', sa.DECIMAL(precision=15, scale=6), nullable=True),
    sa.Column('debt_to_equity', sa.DECIMAL(precision=15, scale=6), nullable=True),
    sa.Column('current_ratio', sa.DECIMAL(precision=15, scale=6), nullable=True),
    sa.Column('quick_ratio', sa.DECIMAL(precision=15, scale=6), nullable=True),
    sa.Column('gross_margin', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('operating_margin', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('net_margin', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('revenue_growth_yoy', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('profit_growth_yoy', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('ebitda_growth_yoy', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('eps_growth_yoy', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('revenue_growth_qoq', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('profit_growth_qoq', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('profit_growth_yoy >= -100', name='valid_profit_growth'),
    sa.CheckConstraint('revenue_growth_yoy >= -100', name='valid_revenue_growth'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_company_report_period', 'fundamental_data', ['company_id', 'report_date', 'period_type'], unique=True)
    op.create_index('idx_market_cap', 'fundamental_data', ['market_cap'], unique=False)
    op.create_index('idx_pe', 'fundamental_data', ['pe_ratio'], unique=False)
    op.create_index('idx_profit_growth_yoy', 'fundamental_data', ['profit_growth_yoy'], unique=False)
    op.create_index('idx_revenue_growth_yoy', 'fundamental_data', ['revenue_growth_yoy'], unique=False)
    op.create_index('idx_roce', 'fundamental_data', ['roce'], unique=False)
    op.create_index('idx_roe', 'fundamental_data', ['roe'], unique=False)
    op.create_table('stock_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.DECIMAL(precision=12, scale=4), nullable=True),
    sa.Column('high', sa.DECIMAL(precision=12, scale=4), nullable=True),
    sa.Column('low', sa.DECIMAL(precision=12, scale=4), nullable=True),
    sa.Column('close', sa.DECIMAL(precision=12, scale=4), nullable=True),
    sa.Column('adjusted_close', sa.DECIMAL(precision=12, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_company_date_unique', 'stock_prices', ['company_id', 'date'], unique=True)
    op.create_index('idx_date', 'stock_prices', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_date', table_name='stock_prices')
    op.drop_index('idx_company_date_unique', table_name='stock_prices')
    op.drop_table('stock_prices')
    op.drop_index('idx_roe', table_name='fundamental_data')
    op.drop_index('idx_roce', table_name='fundamental_data')
    op.drop_index('idx_revenue_growth_yoy', table_name='fundamental_data')
    op.drop_index('idx_profit_growth_yoy', table_name='fundamental_data')
    op.drop_index('idx_pe', table_name='fundamental_data')
    op.drop_index('idx_market_cap', table_name='fundamental_data')
    op.drop_index('idx_company_report_period', table_name='fundamental_data')
    op.drop_table('fundamental_data')
    op.drop_index('idx_last_update_date', table_name='data_update_logs')
    op.drop_index('idx_company_data_type', table_name='data_update_logs')
    op.drop_table('data_update_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_last_activity', table_name='users')
    op.drop_index('idx_users_email_active', table_name='users')
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_market_holidays_date'), table_name='market_holidays')
    op.drop_table('market_holidays')
    op.drop_index(op.f('ix_companies_symbol'), table_name='companies')
    op.drop_index('idx_sector', table_name='companies')
    op.drop_index('idx_market_cap_category', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
